services:
  ymde:
    build: .
    environment:
      - AUDIO_FORMAT=m4a
      - QUALITY=0
      - CONCURRENCY=2
      - REMOVE_VIDEOS_SUFFIX=1
      - PREFER_YOUTUBE_MUSIC=1
      - WRITE_M3U=1
      - VERBOSE=0
      - DRY_RUN=0
      - RATE_LIMIT=
      - SLEEP=
      - COOKIES=/data/cookies.txt
    volumes:
      - ./data:/data
      - ./library:/library
    restart: "no"